// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6wm0SJEujrWvJQtP8p8l7FSTeDt8z_OQ',
    appId: '1:902234051198:web:d0fd7156e98e17f52a7e2f',
    messagingSenderId: '902234051198',
    projectId: 'subway-18f9d',
    authDomain: 'subway-18f9d.firebaseapp.com',
    storageBucket: 'subway-18f9d.appspot.com',
    measurementId: 'G-KBYV2EMB8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOKs5rqKgZzxhc0ESlKVe3BM9hcNkhujs',
    appId: '1:902234051198:android:15fd4abb9a43a5f82a7e2f',
    messagingSenderId: '902234051198',
    projectId: 'subway-18f9d',
    storageBucket: 'subway-18f9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJtir4D_hJJn9rQKWcmkm36gKL0oEVc7A',
    appId: '1:902234051198:ios:418df3e51e10fefe2a7e2f',
    messagingSenderId: '902234051198',
    projectId: 'subway-18f9d',
    storageBucket: 'subway-18f9d.appspot.com',
    iosClientId: '902234051198-aaedb8p2gk6ta8fkguj1egad27d57rmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.projekKelompok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJtir4D_hJJn9rQKWcmkm36gKL0oEVc7A',
    appId: '1:902234051198:ios:418df3e51e10fefe2a7e2f',
    messagingSenderId: '902234051198',
    projectId: 'subway-18f9d',
    storageBucket: 'subway-18f9d.appspot.com',
    iosClientId: '902234051198-aaedb8p2gk6ta8fkguj1egad27d57rmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.projekKelompok',
  );
}
